kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/test"
    #avp.kubernetes.io/kv-version: "2"
type: Opaque
data:
  password: password
